# Satellite publishing identities (ADR-0007 decisions 3, 4, 5; SEAM-3; design
# doc §8 "one SA per satellite scoped to its prefix", §12.2, §12.3).
#
# ONE MAP, NOT ONE-OFF RESOURCES. Every resource below is for_each over
# var.satellites, so adding phd-milestones in Phase 3 is one map entry -- a new
# service account, a new provider, a new impersonation binding and a new
# prefix-scoped bucket binding, with no new module and no edit to this file.
# The map KEY is the source name, and it is the same string three times over:
# the manifest's "source", the bucket prefix sources/<source>/, and the IAM
# condition. SEAM-2 fixes that identity; nothing here may vary it.
#
# Per satellite, and nothing else:
#   1. a service account, which holds NO KEY (§12.2);
#   2. a WIF provider in the satellites pool, admitting only that repository;
#   3. a workloadIdentityUser binding admitting only that repository's default
#      branch;
#   4. a binding of the three-permission custom role (satellite-role.tf) on the
#      content bucket, conditioned to that satellite's own prefix.
#
# A SEPARATE POOL, WHICH IS THE POINT (ADR-0007 decision 5). wif.tf records the
# shared-pool invariant: a principalSet is scoped to the POOL, so the hub's
# deploy binding keeps other repositories out only while EVERY provider in the
# hub's github-actions pool maps attribute.repository_id_ref from
# assertion.repository_id + '/' + assertion.ref. Terraform cannot enforce that.
# Putting satellites in their own pool makes the hub's trust boundary
# structural: no satellite provider exists in the hub's pool at all, so no
# satellite token can even be presented against a hub binding.
#
# The same invariant then applies WITHIN this pool, between satellites -- and
# here it is structural too, because every provider in this pool is generated by
# the single for_each below, from one attribute_mapping. There is no second
# place to add a provider with a different mapping. If a future change adds a
# hand-written provider to this pool, it must carry this exact mapping; prefer
# adding a map entry instead.
#
# Even inside the pool, one satellite cannot impersonate another: each binding
# pins attribute.repository_id_ref to that satellite's own immutable numeric
# repository_id, and repository_id is asserted by GitHub's OIDC issuer, not
# chosen by the workflow.

resource "google_iam_workload_identity_pool" "satellites" {
  project                   = var.project_id
  workload_identity_pool_id = "satellites"
  display_name              = "Satellites"
  description               = "GitHub Actions OIDC identities for satellite repositories that publish to the content bucket. Separate from the hub's github-actions pool so the hub's deploy binding is out of reach (ADR-0007 decision 5)."

  depends_on = [google_project_service.phase1]
}

# One provider per satellite (see the handoff, open question (a): one provider
# per repository beats one provider admitting several, because a provider is the
# unit of both revocation and blast radius).
#
# Admission is decided twice, exactly as the hub's provider decides it:
#
# 1. attribute_condition, here. A token is admitted only if it comes from this
#    repository, matched on its immutable numeric repository_id AND
#    repository_owner_id AND its name. Google: "Using 'name' fields like
#    repository and repository_owner increases the chances of cybersquatting and
#    typosquatting attacks ... use the numeric *_id fields instead, which are
#    unique and can't be reused" (Configure Workload Identity Federation with
#    deployment pipelines, GitHub Actions). The name is kept as well so a
#    transferred or renamed repository stops authenticating until this module is
#    reviewed. pull_request_target is refused outright: it runs with the base
#    branch's ref while handling pull-request input.
# 2. The impersonation binding below, which pins the ref.
#
# cv is a PUBLIC repository (ADR-0008 decision 6), so anyone can open a pull
# request against it. Neither half admits one: a fork's token carries the fork's
# repository_id and fails step 1, and a same-repo pull request carries
# refs/pull/<n>/merge and fails step 2.
resource "google_iam_workload_identity_pool_provider" "satellite" {
  for_each = var.satellites

  project                            = var.project_id
  workload_identity_pool_id          = google_iam_workload_identity_pool.satellites.workload_identity_pool_id
  workload_identity_pool_provider_id = "github-${each.key}"
  display_name                       = "GitHub: ${each.value.repository}"
  description                        = "OIDC tokens from ${each.value.repository} only, publishing as source ${each.key}."

  # attribute.repository_id_ref is the attribute the binding below matches. Its
  # mapping must stay exactly this expression: see the pool invariant above.
  attribute_mapping = {
    "google.subject"                = "assertion.sub"
    "attribute.repository"          = "assertion.repository"
    "attribute.repository_id"       = "assertion.repository_id"
    "attribute.repository_owner_id" = "assertion.repository_owner_id"
    "attribute.ref"                 = "assertion.ref"
    "attribute.repository_id_ref"   = "assertion.repository_id + '/' + assertion.ref"
  }

  attribute_condition = join(" && ", [
    "assertion.repository_id == '${each.value.repository_id}'",
    "assertion.repository_owner_id == '${each.value.repository_owner_id}'",
    "assertion.repository == '${each.value.repository}'",
    "assertion.event_name != 'pull_request_target'",
  ])

  oidc {
    issuer_uri = local.github_oidc_issuer
  }
}

# The publishing identity. It holds no key and no GitHub credential of any kind
# (ADR-0007 decisions 2 and 3): the satellite's workflow exchanges its GitHub
# OIDC token for a short-lived Google token at run time and impersonates this
# account. Nothing here can reach the website repository.
#
# It holds NO project-level role. Its only grant is the conditioned bucket
# binding at the bottom of this file.
resource "google_service_account" "satellite_publish" {
  for_each = var.satellites

  project      = var.project_id
  account_id   = "publish-${each.key}"
  display_name = "Publish ${each.key} (GitHub Actions)"
  description  = "Publishes ${each.value.repository} to gs://${local.content_bucket_name}/sources/${each.key}/ from refs/heads/${each.value.default_branch} via Workload Identity Federation. Has no keys and no access to any other prefix."

  depends_on = [google_project_service.phase1]
}

# Lets GitHub Actions runs on this satellite's DEFAULT BRANCH -- and nothing
# else -- mint short-lived tokens as its publishing service account.
#
# For cv that branch is refs/heads/master, NOT refs/heads/main: cv's default
# branch is master (ADR-0008 decision 6, correcting design doc §2). A binding
# written for main would admit nothing, and cv would fail to publish with an
# authentication error that looks like a misconfigured provider.
#
# Pull request runs carry refs/pull/<n>/merge and other branches carry their own
# ref, so neither can publish.
resource "google_service_account_iam_member" "satellite_publish_wif" {
  for_each = var.satellites

  service_account_id = google_service_account.satellite_publish[each.key].name
  role               = "roles/iam.workloadIdentityUser"
  member             = "principalSet://iam.googleapis.com/${google_iam_workload_identity_pool.satellites.name}/attribute.repository_id_ref/${each.value.repository_id}/refs/heads/${each.value.default_branch}"
}

# The prefix boundary itself (ADR-0007 decision 4; SEAM-3).
#
# The three-permission custom role from satellite-role.tf, bound on the CONTENT
# BUCKET (not the project), conditioned so it applies only to objects whose name
# begins with this satellite's own prefix.
#
# This condition is load-bearing twice over:
#
# - It only works because uniform_bucket_level_access is true on the bucket
#   (storage.tf). Without it the condition does not apply and this grant covers
#   every object in the bucket.
# - It cannot be escaped by a crafted object name. Cloud Storage's namespace is
#   flat: an object called "sources/cv/../phd-milestones/x" is a single literal
#   name that still startsWith "sources/cv/", not a traversal out of the prefix.
#   (The publish action rejects such paths anyway, ADR-0002, but the boundary
#   here does not depend on that.)
#
# The role carries no storage.objects.list, so this identity cannot enumerate
# the bucket -- not its own prefix, and not anyone else's. That is deliberate
# and must stay that way: list cannot be prefix-restricted at all. See
# satellite-role.tf for the full reasoning and the primary source.
resource "google_storage_bucket_iam_member" "satellite_publish_prefix" {
  for_each = var.satellites

  bucket = google_storage_bucket.content.name
  role   = google_project_iam_custom_role.satellite_publisher.name
  member = google_service_account.satellite_publish[each.key].member

  condition {
    title       = "only-sources-${each.key}"
    description = "Objects under sources/${each.key}/ of this bucket only (ADR-0007 decision 4). Requires uniform bucket-level access."
    expression = join(" && ", [
      "resource.type == 'storage.googleapis.com/Object'",
      "resource.name.startsWith('projects/_/buckets/${google_storage_bucket.content.name}/objects/sources/${each.key}/')",
    ])
  }
}
